name: "Base vRPex Rework Clean"
author: "ChatGPT"
description: "Base limpa e estável do FiveM com vRPex Rework, oxmysql e scripts básicos (login, spawn e HUD)."
version: 1.0.0

tasks:
  # ===============================
  #  DOWNLOAD DOS FRAMEWORKS
  # ===============================
  - action: download_github
    src: "https://github.com/overextended/oxmysql"
    dest: "./resources/[system]/oxmysql"

  - action: download_github
    src: "https://github.com/ImagicTheCat/vRP"
    dest: "./resources/[vrp]/vrp"

  # ===============================
  #  DOWNLOAD DE SCRIPTS BÁSICOS
  # ===============================
  - action: download_github
    src: "https://github.com/renzuzu/vRP_Identity"
    dest: "./resources/[vrp]/vrp_identity"

  - action: download_github
    src: "https://github.com/renzuzu/vRP_Spawn"
    dest: "./resources/[vrp]/vrp_spawn"

  - action: download_github
    src: "https://github.com/renzuzu/vRP_Hud"
    dest: "./resources/[vrp]/vrp_hud"

  # ===============================
  #  CONFIGURAÇÃO DO SERVER.CFG
  # ===============================
  - action: write_file
    path: "./server.cfg"
    data: |
      ###########################################
      # SERVER INFO
      ###########################################
      endpoint_add_tcp "0.0.0.0:30120"
      endpoint_add_udp "0.0.0.0:30120"
      sv_hostname "Base vRPex Clean RP"
      sv_maxclients 64
      sv_licenseKey "COLOQUE_SUA_LICENSE_KEY_AQUI"
      sv_enforceGameBuild 2944
      sv_scriptHookAllowed 0

      ###########################################
      # DATABASE (OXMYSQL)
      ###########################################
      set mysql_connection_string "mysql://root@localhost/vrpex?charset=utf8mb4"

      ###########################################
      # RECURSOS BASE DO FIVEM
      ###########################################
      ensure mapmanager
      ensure chat
      ensure spawnmanager
      ensure sessionmanager
      ensure hardcap
      ensure baseevents

      ###########################################
      # FRAMEWORK
      ###########################################
      ensure oxmysql
      ensure vrp

      ###########################################
      # SCRIPTS BÁSICOS
      ###########################################
      ensure vrp_identity
      ensure vrp_spawn
      ensure vrp_hud

      ###########################################
      # CONFIG EXTRA
      ###########################################
      add_ace resource.vrp command.add_ace allow
      add_ace resource.vrp command.add_principal allow
      add_ace resource.vrp command.remove_principal allow
      add_ace resource.vrp command.execute allow

  # ===============================
  #  CRIAÇÃO DO BANCO DE DADOS
  # ===============================
  - action: connect_database
    connection_string: "mysql://root@localhost/vrpex?charset=utf8mb4"

  - action: query_database
    file: "./resources/[vrp]/vrp/sql/mysql.sql"

  # ===============================
  #  VERIFICAÇÃO FINAL
  # ===============================
  - action: ensure_resource
    resource: "oxmysql"

  - action: ensure_resource
    resource: "vrp"

  - action: write_file
    path: "./README.txt"
    data: |
      ✅ Base vRPex instalada com sucesso!
      Banco de dados: vrpex
      Usuário: root (sem senha)
      Framework: vRPex Rework
      Scripts incluídos: login, spawn, hud
      👉 Configure sua license key no server.cfg e inicie o servidor pelo txAdmin.
