name: "Base vRPex Clean Minimal"
author: "ChatGPT"
description: "Base limpa do FiveM com vRPex Rework e scripts básicos."
version: 1.0.0

tasks:
  - action: download_github
    src: "https://github.com/overextended/oxmysql"
    dest: "./resources/[system]/oxmysql"

  - action: download_github
    src: "https://github.com/ImagicTheCat/vRP"
    dest: "./resources/[vrp]/vrp"

  - action: download_github
    src: "https://github.com/renzuzu/vRP_Identity"
    dest: "./resources/[vrp]/vrp_identity"

  - action: download_github
    src: "https://github.com/renzuzu/vRP_Spawn"
    dest: "./resources/[vrp]/vrp_spawn"

  - action: download_github
    src: "https://github.com/renzuzu/vRP_Hud"
    dest: "./resources/[vrp]/vrp_hud"

  - action: ensure_resource
    resource: "oxmysql"

  - action: ensure_resource
    resource: "vrp"

  - action: ensure_resource
    resource: "vrp_identity"

  - action: ensure_resource
    resource: "vrp_spawn"

  - action: ensure_resource
    resource: "vrp_hud"
